### ISSUE TITLE
Is it okay to translate it into Korean and use it?

### ISSUE THREAD

**Issue by hongbeomi** [ZieIony/GuideToCustomViews#3]
Thank you for the good guide!🙌 I want to let Koreans know

**Comment by ZieIony** [comment]
I see one problem with that - I'm updating the existing articles (fix issues) and adding new content from time to time, so translating it is one thing, but keeping it up to date is a different story. I'm currently working on drawables and accessibility, but I don't know when these will be ready.

If you can update translations or you can live with just one snapshot translation, then I'm ok with you translating it. Just link to the original repo, please.

**Comment by hongbeomi** [comment]
Ok Thank you!
